# Generated by Django 5.1.1 on 2024-09-30 01:39

import django.contrib.postgres.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("maps", "0002_place_reviews"),
    ]

    operations = [
        migrations.AlterField(
            model_name="place",
            name="reviews",
            field=django.contrib.postgres.fields.ArrayField(
                base_field=models.TextField(max_length=300),
                blank=True,
                default=list,
                size=None,
            ),
        ),
    ]
