# Generated by Django 5.1.1 on 2024-09-30 02:25

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
  dependencies = [
    ('maps', '0003_alter_place_reviews'),
    migrations.swappable_dependency(settings.AUTH_USER_MODEL),
  ]

  operations = [
    migrations.RemoveField(
      model_name='place',
      name='reviews',
    ),
    migrations.AlterField(
      model_name='placereview',
      name='user',
      field=models.ForeignKey(
        on_delete=django.db.models.deletion.CASCADE,
        related_name='place_reviews',
        to=settings.AUTH_USER_MODEL,
      ),
    ),
  ]
