# Generated by Django 5.1.1 on 2024-09-30 04:22

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("maps", "0004_remove_place_reviews_alter_placereview_user"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name="placereview",
            name="place",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="reviews_for_place",
                to="maps.place",
            ),
        ),
        migrations.AlterField(
            model_name="placereview",
            name="user",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="reviews_for_user",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
    ]
