# Generated by Django 5.1.1 on 2024-09-18 19:43

import django.contrib.postgres.fields
from django.db import migrations, models

import maps.models


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="UserProfile",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "favorite_restauraunts",
                    django.contrib.postgres.fields.ArrayField(
                        base_field=maps.models.Place(), max_length=10, size=None
                    ),
                ),
            ],
        ),
    ]
