# Generated by Django 5.1.1 on 2024-09-30 05:19

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("users", "0002_alter_userprofile_favorite_places"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="userprofile",
            name="favorite_places",
        ),
        migrations.AddField(
            model_name="userprofile",
            name="favorite_places",
            field=models.JSONField(blank=True, default=list),
        ),
    ]
